name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v6.0.2
      with:
        mayor_patter: "mayor:"
        minor_patter: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: versionSemantica   
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: | 
        echo "usuario cambiado !!!!"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION !!!!"

    - name: Build the Docker image
      env:
        NEW_VERSION: ${{ steps.versionSemantica.outputs.version }}
      run: |
        docker build -t fernandoblesa/docker-graphql:$NEW_VERSION .
        docker build -t fernandoblesa/docker-graphql:latest .

    - name: Push the Docker image
      env:
        NEW_VERSION: ${{ steps.versionSemantica.outputs.version }}
      run: |
        docker push fernandoblesa/docker-graphql:$NEW_VERSION
        docker push fernandoblesa/docker-graphql:latest

        
